version: '3'
services:
  streamlit:
    build: .
    command: streamlit run src/app.py
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    ports:
      - "8501:8501"
    volumes:
      - ./:/root
